### PR TITLE
Changelog package improvements

### PR DESCRIPTION
**Pull request by ezzatron**
Here's my take on some easy improvements to the `changelog` package. Rather than describe every change, I think an output comparison is easier:

**Before:**

```
vX.Y.Z
<!-- Previous tag: v0.21.2 -->

### Added

- unreleased addition
- another unreleased addition

### Changed

- unreleased change
- another unreleased change

<!------------------ Everything past this line will be deleted ----------------------->

### Added

- implement
- add

### Changed

- rename
- convert
- refactor
- migrate
- change

### Removed

- remove

### Fixed

- ensure
- fix

### Deprecated

- deprecate

### Security

- vulnerability
- security

### Other

- baz
- bar
- foo
- issue
- bug
- revert
- delete
```

**After:**

```
vX.Y.Z

### Added

- unreleased addition
- another unreleased addition
- implement
- add

### Changed

- unreleased change
- another unreleased change
- rename
- convert
- refactor
- migrate
- change

### Deprecated

- deprecate

### Removed

- revert
- delete
- remove

### Fixed

- issue
- ensure
- fix
- bug

### Security

- vulnerability
- security

<!------------------------------------ >8 --------------------------------------

Previous tag: v0.21.2

Uncategorized commits:

- baz
- bar
- foo
```

One thing I'd also love to do, but couldn't figure out, is how to remove the `Unreleased` section once it's been released, rather than replacing it with an empty one. We basically never use that section, and it just makes our change logs look worse 99.9% of the time.

### CODE REVIEW

**Comment by danilvpetrov** [comment]
LGTM, I like the scissor marker for simplicity.

**Review by danilvpetrov — APPROVED** [review]

**Comment by jmalloc** [comment]
Totally subjective things incoming:

> We basically never use that section,

I use it all the time. I strongly prefer to write changelog entries as you commit the changes, though I realise that process is funky when using the `mob` tool.

Separately, putting the commit messages outside the automatically-removed section might make it tempting to just use the commit messages unedited. I'll die on the "commit messages don't make a good changelog" hill, so I'd opt to keep them as a reminder/prompt but would prefer to move away from anything that suggests that they ARE the changelog entries.  I also realise that your (@ezzatron) commit message discipline is much stronger than... well,  anyone! 😉 

All that said, this change affects me least of anybody so I wouldn't block this PR as is.

**Comment by ezzatron** [comment]
> I use it all the time. I strongly prefer to write changelog entries as you commit the changes, though I realise that process is funky when using the `mob` tool.

I should have clarified that this PR doesn't affect the unreleased section at all. And all I want (in another PR) is for it not to create that section automatically. I don't want to remove the option to use it. I just think it's pretty easy to manually add an `## Unreleased` header as needed, and having and empty section looks bad.

> Separately, putting the commit messages outside the automatically-removed section might make it tempting to just use the commit messages unedited.

Yeah, I totally agree, and I've expressed pretty much the exact same sentiment in the past. The issue we keep running in to is that folks are editing the change log entries, and then forgetting to remove the cut marker, resulting in empty tag annotations.

Perhaps there's a better solution where `make tag` simply doesn't proceed unless you put _something_ in the annotation body. But then there's the issue that all your hard work manually editing entries disappears into the ether if you forget the cut marker.

**Review by jmalloc — APPROVED** [review]

**Review by Nekroze — APPROVED** [review]

**Review by dezlitz — APPROVED** [review]

**Comment by dezlitz** [comment]
Yeah we are the same we haven't really been using the unreleased section since we got used to the mob tool.

**Pull request merged**
